### PR TITLE
Mimic Tree UI of ChatGPT

### PR DESCRIPTION
**Pull request by RossHartmann**
I reviewed ChatGPT's UI and this PR makes it so that the tree UI now mimics ChatGPT's implementation.

Please review and merge when ready. Thank you @littlemoonstones!

### CODE REVIEW

**Comment by littlemoonstones** [comment]
Thanks! However, in mobile view, I found that the button extends beyond the screen. I will try to fix it later.
image

**Comment by RossHartmann** [comment]
> Thanks! However, in mobile view, I found that the button extends beyond the screen. I will try to fix it later. image

Ah great catch, thank you!

**Comment by littlemoonstones** [comment]
Sorry, I'm not sure how to merge my branch (mimic_tree) into your PR. Could you please merge b2476f4e666a81db168cb923d53e6d334278f0d0 into your PR instead? I'm not certain if this is the correct course of action.

## Desktop
desktop

## Mobile
mobile

**Comment by RossHartmann** [comment]
@littlemoonstones Just merged your changes into this PR! Feel free to review and merge if you like it in its current state

**Comment by littlemoonstones** [comment]
OK, thanks!

**Pull request merged**
